"""Submit a patch as a pull request to the upstream library."""

import os
import re
import subprocess
import tempfile
from pathlib import Path

from github import Github, GithubException


def _extract_diff(analysis_text: str) -> str | None:
    match = re.search(r"```diff\n(.*?)```", analysis_text, re.DOTALL)
    return match.group(1).strip() if match else None


def submit_pr(result: dict, solution_path: Path) -> str | None:
    """
    Fork the repo, apply the patch, and open a PR.
    Returns the PR URL or None if skipped/failed.
    """
    token = os.environ.get("GITHUB_TOKEN")
    if not token:
        print("  [submit] No GITHUB_TOKEN — skipping PR submission")
        return None

    diff = _extract_diff(result["analysis"])
    if not diff:
        print("  [submit] No diff block found in analysis — skipping")
        return None

    issue = result["issue"]
    org = issue["repo"]["org"]
    name = issue["repo"]["name"]
    number = issue["number"]
    title = issue["title"]

    gh = Github(token)
    upstream = gh.get_repo(f"{org}/{name}")
    me = gh.get_user()

    # Fork if needed
    try:
        fork = me.get_repo(name)
    except GithubException:
        fork = me.create_fork(upstream)
        print(f"  [submit] Forked {org}/{name} → {me.login}/{name}")

    branch = f"fix/issue-{number}"
    default_branch = upstream.default_branch

    with tempfile.TemporaryDirectory() as tmpdir:
        clone_url = f"git@github.com:{me.login}/{name}.git"
        subprocess.run(["git", "clone", "--depth", "1", clone_url, tmpdir], check=True, capture_output=True)

        # Write and apply the patch
        patch_file = Path(tmpdir) / "fix.patch"
        patch_file.write_text(diff)

        apply = subprocess.run(
            ["git", "apply", "--check", str(patch_file)],
            cwd=tmpdir, capture_output=True
        )
        if apply.returncode != 0:
            print(f"  [submit] Patch does not apply cleanly — skipping: {apply.stderr.decode()}")
            return None

        subprocess.run(["git", "apply", str(patch_file)], cwd=tmpdir, check=True, capture_output=True)
        subprocess.run(["git", "checkout", "-b", branch], cwd=tmpdir, check=True, capture_output=True)
        subprocess.run(["git", "add", "-A"], cwd=tmpdir, check=True, capture_output=True)
        subprocess.run(
            ["git", "commit", "-m", f"fix: address issue #{number} - {title[:60]}"],
            cwd=tmpdir, check=True, capture_output=True
        )
        subprocess.run(["git", "push", "origin", branch], cwd=tmpdir, check=True, capture_output=True)

    body = (
        f"Fixes #{number}\n\n"
        f"This PR was generated by [ai-lib-contrib](https://github.com/{me.login}/ai-lib-contrib) "
        f"after automated analysis of the bug report.\n\n"
        f"**Analysis summary:**\n\n"
        + result["analysis"][:1500]
        + f"\n\n[Full analysis]({solution_path})"
    )

    try:
        pr = upstream.create_pull(
            title=f"fix: {title[:70]}",
            body=body,
            head=f"{me.login}:{branch}",
            base=default_branch,
        )
        print(f"  [submit] PR opened: {pr.html_url}")
        return pr.html_url
    except GithubException as e:
        print(f"  [submit] Failed to open PR: {e}")
        return None
